config-version: 1

Compatibility:
  PlaceholderAPI: true

VanillaFood-Settings:
  Cooldown: #Available Type values: [global, personal, disable]
    Type: 'disable'
    Global-Cooldown: 3

CustomFood-Settings:
  Cooldown: #Available Type values: [global, personal, disable]
    Type: 'disable'
    Global-Cooldown: 3
  PlayerHead:
    DisablePlace: true
  AutoUpdateInventory: #These options may affect server performance. If possible, use commands or higher values
    Enabled: false
    UpdateTicks: 20