config-version: 1

Compatibility:
  PlaceholderAPI: true

VanillaFood-Settings:
  Cooldown: #Available Type values: [global, personal, disable]
    Type: 'disable'
    Global-Cooldown: 3

CustomFood-Settings:
  Cooldown: #Available Type values: [global, personal, disable]
    Type: 'disable'
    Global-Cooldown: 3
  PlayerHead:
    DisablePlace: true