name: ConsumeFood2
version: '1.0' #'${project.version}'
main: me.msicraft.consumefood2.ConsumeFood2
api-version: '1.16'
authors: [msicraft]
softdepend: [PlaceholderAPI]
commands:
  consumefood2:
    description: Main command
    aliases: [consumefood2, consume2, cf2]